# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'iOS-Developer-Challenge' do
pod 'Argo'
pod 'JSONModel'
source 'https://github.com/CocoaPods/Specs.git'
pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '~> 2.2.0'

end

